In [ ]:
import pandas as pd
na_values = 
df = pd.read_csv('results.csv',index_col='Respondent')
schema_df = pd.read_csv('schema.csv',index_col='Column')

In [2]:
pd.set_option('display.max_columns',85)
pd.set_option("display.max_rows",85)

In [18]:
df['COUNTRY'] = df['COUNTRY'].str.lower()
df

,MAINBRANCH,HOBBYIST,OPENSOURCER,OPENSOURCE,EMPLOYMENT,COUNTRY,STUDENT,EDLEVEL,UNDERGRADMAJOR,EDUOTHER,ORGSIZE,DEVTYPE,YEARSCODE,AGE1STCODE,YEARSCODEPRO,CAREERSAT,JOBSAT,MGRIDIOT,MGRMONEY,MGRWANT,JOBSEEK,LASTHIREDATE,LASTINT,FIZZBUZZ,JOBFACTORS,RESUMEUPDATE,CURRENCYSYMBOL,CURRENCYDESC,COMPTOTAL,COMPFREQ,CONVERTEDCOMP,WORKWEEKHRS,WORKPLAN,WORKCHALLENGE,WORKREMOTE,WORKLOC,IMPSYN,CODEREV,CODEREVHRS,UNITTESTS,PURCHASEHOW,PURCHASEWHAT,LANGUAGEWORKEDWITH,LANGUAGEDESIRENEXTYEAR,DATABASEWORKEDWITH,DATABASEDESIRENEXTYEAR,PLATFORMWORKEDWITH,PLATFORMDESIRENEXTYEAR,WEBFRAMEWORKEDWITH,WEBFRAMEDESIRENEXTYEAR,MISCTECHWORKEDWITH,MISCTECHDESIRENEXTYEAR,DEVENVIRON,OPSYS,CONTAINERS,BLOCKCHAINORG,BLOCKCHAINIS,BETTERLIFE,ITPERSON,OFFON,SOCIALMEDIA,EXTRAVERSION,SCREENNAME,SOVISIT1ST,SOVISITFREQ,SOVISITTO,SOFINDANSWER,SOTIMESAVED,SOHOWMUCHTIME,SOACCOUNT,SOPARTFREQ,SOJOBS,ENTTEAMS,SOCOMM,WELCOMECHANGE,SONEWCONTENT,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,DEPENDENTS,SURVEYLENGTH,SURVEYEASE
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",united kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",bosnia and herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,united states,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [28]:
 df.rename(columns ={'CONVERTEDCOMP':'Salary'},inplace=True)

In [30]:
df['Salary']

Respondent
1            NaN
2            NaN
3         8820.0
4        61000.0
5            NaN
          ...
88377        NaN
88601        NaN
88802        NaN
88816        NaN
88863        NaN
Name: Salary, Length: 88883, dtype: float64

In [45]:
df.columns = df.columns.str.lower()

In [54]:

df.sort_values(by=['country','salary'],ascending = [True,False],inplace=True)
df[['country','salary']].head()

                country     salary
Respondent
63129       afghanistan  1000000.0
50499       afghanistan   153216.0
39258       afghanistan    19152.0
58450       afghanistan    17556.0
7085        afghanistan    14364.0

In [55]:
df['salary'].fillna(0)

Respondent
63129    1000000.0
50499     153216.0
39258      19152.0
58450      17556.0
7085       14364.0
           ...
88062          0.0
88076          0.0
88601          0.0
88802          0.0
88816          0.0
Name: salary, Length: 88883, dtype: float64

In [57]:
df['salary'].median()

np.float64(57287.0)

In [65]:
country_grp = df.groupby(['country'])
df['country'].value_counts(normalize=True)

country
united states                       0.236042
india                               0.102095
germany                             0.066095
united kingdom                      0.064642
canada                              0.038253
                                      ...
north korea                         0.000011
niger                               0.000011
saint vincent and the grenadines    0.000011
chad                                0.000011
brunei darussalam                   0.000011
Name: proportion, Length: 179, dtype: float64

In [77]:
country_grp['salary'].agg(['median','mean'])

                                        median           mean
country
afghanistan                             6222.0  101953.333333
albania                                10818.0   21833.700000
algeria                                 7878.0   34924.047619
andorra                               160931.0  160931.000000
angola                                  7764.0    7764.000000
...                                        ...            ...
venezuela, bolivarian republic of...    6384.0   14581.627907
viet nam                               11892.0   17233.436782
yemen                                  11940.0   16909.166667
zambia                                  5040.0   10075.375000
zimbabwe                               19200.0   34046.666667

[179 rows x 2 columns]

In [94]:
country_uses_python = country_grp['languageworkedwith'].apply(lambda x: (x.str.contains('Python').sum()))
country_uses_python

country
afghanistan                              8
albania                                 23
algeria                                 40
andorra                                  0
angola                                   2
                                        ..
venezuela, bolivarian republic of...    28
viet nam                                78
yemen                                    3
zambia                                   4
zimbabwe                                14
Name: languageworkedwith, Length: 179, dtype: int64

In [93]:
country_respondents = df['country'].value_counts()
country_respondents

country
united states                       20949
india                                9061
germany                              5866
united kingdom                       5737
canada                               3395
                                    ...
north korea                             1
niger                                   1
saint vincent and the grenadines        1
chad                                    1
brunei darussalam                       1
Name: count, Length: 179, dtype: int64

In [95]:
country_uses_python/country_respondents

country
afghanistan                             0.181818
albania                                 0.267442
algeria                                 0.298507
andorra                                 0.000000
angola                                  0.400000
                                          ...
venezuela, bolivarian republic of...    0.318182
viet nam                                0.337662
yemen                                   0.157895
zambia                                  0.333333
zimbabwe                                0.358974
Length: 179, dtype: float64

In [102]:
python_df = pd.concat([country_uses_python,country_respondents],axis='columns',sort=False)
python_df

                                      languageworkedwith  count
country
afghanistan                                            8     44
albania                                               23     86
algeria                                               40    134
andorra                                                0      7
angola                                                 2      5
...                                                  ...    ...
venezuela, bolivarian republic of...                  28     88
viet nam                                              78    231
yemen                                                  3     19
zambia                                                 4     12
zimbabwe                                              14     39

[179 rows x 2 columns]

In [107]:
python_df.rename(columns={'languageworkedwith':'KnowsPython','count':'Respondants'},inplace=True)

In [116]:
python_df['pctknowspython'] = round((((python_df['KnowsPython'])/python_df['Respondants'])*100),2)

In [117]:
python_df.sort_values('pctknowspython',ascending=False)

                                  KnowsPython  Respondants  pctknowspython
country
dominica                                    1            1          100.00
niger                                       1            1          100.00
timor-leste                                 1            1          100.00
sao tome and principe                       1            1          100.00
turkmenistan                                6            7           85.71
...                                       ...          ...             ...
tonga                                       0            1            0.00
north korea                                 0            1            0.00
papua new guinea                            0            1            0.00
tajikistan                                  0            7            0.00
lao people's democratic republic            0            3            0.00

[179 rows x 3 columns]

In [118]:
python_df.loc['japan']

KnowsPython       182.00
Respondants       391.00
pctknowspython     46.55
Name: japan, dtype: float64

In [124]:
df['yearscode'].unique()

array(['Less than 1 year', '7', '2', '6', '3', '4', '10', '36', '1', nan,
       'More than 50 years', '20', '9', '5', '8', '31', '28', '15', '13',
       '12', '17', '18', '21', '35', '14', '25', '11', '19', '22', '23',
       '40', '39', '30', '43', '27', '33', '29', '24', '34', '16', '32',
       '26', '38', '44', '41', '45', '37', '47', '42', '46', '48', '50',
       '49'], dtype=object)

In [127]:
df['yearscode'].replace('Less than 1 year',0,inplace=True)
df['yearscode'].replace('More than 50 years',51,inplace=True)

In [129]:
df['yearscode'].astype(float).mean()

np.float64(11.662114216834588)

In [135]:
flit = df['country'] == 'india'
india_df = df[flit]
india_df.to_csv('data_modified.csv')